# Generated by Django 4.2.4 on 2023-08-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_data_posted_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='pnulished_date',
        ),
    ]
