# Generated by Django 4.2.4 on 2023-08-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_date_posted_post_pnulished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pnulished_date',
            new_name='published_date',
        ),
    ]
