# Generated by Django 4.2.4 on 2023-08-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
